# Generated by Django 6.0.4 on 2026-08-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
    ]
