# Generated by Django 6.0.4 on 2026-08-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_unique_open_order_per_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_received',
        ),
    ]
